name: "Build Github Pages"

on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx
          
      - uses: ammaraskar/sphinx-action@master
        with:
          build-command: "make github"
          docs-folder: "docs/source"
