name: "Build Github Pages"

on:
  push:
    branches: 
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
